// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdtewnyuukxnjtmlahqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkdGV3bnl1dWt4bmp0bWxhaHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTI1OTMsImV4cCI6MjA3MDgyODU5M30.gEGafwN1H7UqCFnFoai7H0pMqIWwu3iVyWgNHAeX-xc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});